"""Which CTFd API routes are for administrators, read from CTFd's own source, and the nginx rules built from them.

Why: the admin allow-list in nginx protects /admin, but almost every administrator action goes through /api/v1, which any
address can reach. nginx therefore treats these requests as "admin surface" and answers them only for the organisers'
addresses (see deploy/nginx/nginx.conf):

  1. any request that carries an Authorization header (API tokens are for organisers and tools, never for players' browsers);
  2. any route CTFd guards with @admins_only, whatever the method;
  3. any write (POST, PUT, PATCH, DELETE) that is NOT on the short list of writes a signed-in player really makes.

Rule 3 fails closed: a write route added by a future CTFd release or plugin is admin-only until someone lists it.

The two generated files are deploy/nginx/snippets/api-admin-routes.conf and api-player-writes.conf. They are checked in; the
integration tests regenerate them from the running image and fail when they differ, so a CTFd upgrade cannot silently leave
a new admin route open.

    python -m l3mon api-rules generate [--image l3mon/ctfd:dev]    rewrite the two files from the image
    python -m l3mon api-rules check    [--image l3mon/ctfd:dev]    exit 1 when the files are out of date

Everything above `# ---- runs inside the image` also runs inside the CTFd container (it needs only the standard library).
"""
from __future__ import annotations

import ast
import json
import re
import subprocess
import sys
from pathlib import Path

WRITES = ("post", "put", "patch", "delete")
METHODS = ("get",) + WRITES
HEADER = (
    "# GENERATED by `python -m l3mon api-rules generate` from CTFd's own source. Do not edit by hand.\n"
    "# {what}\n"
)


# ---- runs inside the image -------------------------------------------------------------------------------------------
def _namespace_prefixes(api_init: str) -> dict[str, str]:
    prefixes = {}
    for node in ast.walk(ast.parse(api_init)):
        if isinstance(node, ast.Call) and isinstance(node.func, ast.Attribute) and node.func.attr == "add_namespace" and len(node.args) >= 2:
            prefixes[ast.unparse(node.args[0])] = ast.literal_eval(node.args[1])
    return prefixes


def _guard(decorators: list[str]) -> str:
    joined = " ".join(decorators)
    if "admins_only" in joined:
        return "admin"
    if any(name in joined for name in ("authed_only", "require_verified_emails", "require_complete_profile")):
        return "player"
    return "open"


def extract(root: str = "/opt/CTFd") -> list[dict]:
    """Every (method, path, guard) CTFd's v1 API defines, in a stable order."""
    base = Path(root) / "CTFd" / "api"
    prefixes = _namespace_prefixes((base / "__init__.py").read_text(encoding="utf-8"))
    found = set()
    for source in sorted((base / "v1").glob("*.py")):
        for cls in [n for n in ast.walk(ast.parse(source.read_text(encoding="utf-8"))) if isinstance(n, ast.ClassDef)]:
            routes = []
            for dec in cls.decorator_list:
                if isinstance(dec, ast.Call) and isinstance(dec.func, ast.Attribute) and dec.func.attr == "route":
                    prefix = prefixes.get(ast.unparse(dec.func.value))
                    if prefix is not None:
                        routes.append(prefix + (ast.literal_eval(dec.args[0]) if dec.args else ""))
            for fn in cls.body:
                if isinstance(fn, ast.FunctionDef) and fn.name in METHODS:
                    guard = _guard([ast.unparse(d).split("(")[0] for d in fn.decorator_list])
                    for path in routes:
                        found.add((fn.name.upper(), "/api/v1" + path, guard))
    return [{"method": m, "path": p, "guard": g} for m, p, g in sorted(found)]


# ---- runs on the host ------------------------------------------------------------------------------------------------
def _is_variable(segment: str) -> bool:
    return segment.startswith("<")


def _literals_shadowing(route: dict, index: int, routes: list[dict]) -> list[str]:
    """Fixed words other routes (same method) have where this route has a variable, e.g. `me` next to /teams/<team_id>/members.

    CTFd (Flask) tries the fixed word first, so `/teams/me/members` is NOT the route `/teams/<team_id>/members`; a regular
    expression for the variable must say so, or a player's own route would be taken for an administrator's.
    """
    parts = route["path"].split("/")
    words = set()
    for other in routes:
        if other["method"] != route["method"]:
            continue
        theirs = other["path"].split("/")
        if len(theirs) != len(parts) or _is_variable(theirs[index]):
            continue
        if all(theirs[j] == parts[j] or _is_variable(theirs[j]) or _is_variable(parts[j]) for j in range(index)):
            words.add(theirs[index])
    return sorted(words)


def to_regex(route: dict, routes: list[dict]) -> str:
    """A CTFd route such as /teams/<int:team_id>/members as an nginx regular expression."""
    out = []
    for index, segment in enumerate(route["path"].split("/")):
        if not _is_variable(segment):
            out.append(re.escape(segment) if segment else segment)
            continue
        base = "[0-9]+" if segment.startswith("<int:") else ".+" if segment.startswith("<path:") else "[^/]+"
        words = _literals_shadowing(route, index, routes)
        out.append((f"(?!(?:{'|'.join(re.escape(w) for w in words)})(?:/|$))" if words else "") + base)
    return "/".join(out)


def render(routes: list[dict]) -> dict[str, str]:
    """The two snippet files' contents."""
    admin = sorted({f"{r['method']}:{to_regex(r, routes)}" for r in routes if r["guard"] == "admin"})
    player = sorted({f"{r['method']}:{to_regex(r, routes)}" for r in routes if r["guard"] != "admin" and r["method"].lower() in WRITES})
    files = {
        "api-admin-routes.conf": HEADER.format(what="Routes CTFd itself guards with @admins_only (any method). Lines are map entries for $api_admin_route."),
        "api-player-writes.conf": HEADER.format(what="Writes a signed-in player makes (everything else that writes is admin surface). Map entries for $api_player_write."),
    }
    files["api-admin-routes.conf"] += "".join(f'"~^{line}/?$" 1;\n' for line in admin)
    files["api-player-writes.conf"] += "".join(f'"~^{line}/?$" 1;\n' for line in player)
    return files


def routes_from_image(image: str) -> list[dict]:
    source = Path(__file__).read_text(encoding="utf-8")
    code = source + "\nprint(json.dumps(extract()))\n"
    done = subprocess.run(["docker", "run", "--rm", "-i", "--entrypoint", "python", image, "-"], input=code, capture_output=True, text=True, timeout=180)
    if done.returncode != 0:
        raise RuntimeError(f"could not read CTFd's routes from {image}: {done.stderr.strip()}")
    return json.loads(done.stdout)


def snippets_dir() -> Path:
    return Path(__file__).resolve().parents[2] / "deploy" / "nginx" / "snippets"


def generate(image: str, directory: Path | None = None) -> list[str]:
    directory = directory or snippets_dir()
    changed = []
    for name, text in render(routes_from_image(image)).items():
        path = directory / name
        if not path.exists() or path.read_text(encoding="utf-8") != text:
            path.write_text(text, encoding="utf-8", newline="\n")
            changed.append(name)
    return changed


def stale(image: str, directory: Path | None = None) -> list[str]:
    directory = directory or snippets_dir()
    return [name for name, text in render(routes_from_image(image)).items() if not (directory / name).exists() or (directory / name).read_text(encoding="utf-8").replace("\r\n", "\n") != text]


def main(argv: list[str]) -> int:
    action = argv[0] if argv else ""
    image = argv[argv.index("--image") + 1] if "--image" in argv else "l3mon/ctfd:dev"
    if action == "generate":
        changed = generate(image)
        print("rewrote: " + ", ".join(changed) if changed else "already up to date")
        return 0
    if action == "check":
        old = stale(image)
        if old:
            print("out of date (run `python -m l3mon api-rules generate`): " + ", ".join(old), file=sys.stderr)
            return 1
        print("api-admin-routes.conf and api-player-writes.conf match CTFd's source in " + image)
        return 0
    print("usage: python -m l3mon api-rules generate|check [--image IMAGE]", file=sys.stderr)
    return 2
